Repository stelace/stelace, pull requests merged in 2019-10, with the labels that each got.

#18 fix(pricing): edge cases with division by zero
  src/util/pricing.js
  test/unit/util/pricing.spec.js
  test/unit/util/transaction.spec.js
Labels: Type: Bug

#22 feat(Event): metadata filter
  src/routes/event.js
  src/services/document.js
  src/services/event.js
  src/util/listQueryBuilder.js
  src/versions/validation/event.js
  test/fixtures/data.js
  test/integration/api/document.spec.js
  test/integration/api/event.spec.js
Labels: Type: Feature

#23 refactor(routes)!: move route flags to route objects
  plugins/stripe/index.js
  plugins/stripe/routes/stripe.js
  plugins/stripe/services/stripe.js
  server.js
Labels: type: Refactor

#24 refactor: isolate exports
  docs/plugins.md
  index.js
  server.js
Labels: type: Refactor

#31 test(email): tests may break if DEBUG_EMAILS is set
  plugins/email/test/email.spec.js
Labels: type: Test

#34 refactor(plugins): use installed copy
  Dockerfile.prod
  docs/plugins.md
  package.json
  plugins/index.js
  scripts/installExternalPlugins.js
  scripts/prepareInstalledPlugins.js
Labels: type: Refactor

#35 fix!: inconsistent moment timezone instead of UTC
  plugins/email/util/handlebars.js
  src/crons/checkESReindex.js
  src/services/availability.js
  src/util/time.js
  test/unit/util/time.spec.js
Labels: type: Bug

#36 Aggregations
  plugins/rating/test/rating.spec.js
  plugins/serverTooling.js
  src/permissions.js
  src/routes/event.js
  src/services/document.js
  src/services/event.js
  src/util/listQueryBuilder.js
  src/util/math.js
  src/util/pricing.js
  src/versions/validation/event.js
  test/fixtures/data.js
  test/integration/api/document.spec.js
  test/integration/api/event.spec.js
  test/unit/util/math.spec.js
  test/util.js
Labels: type: Feature
